### ISSUE TITLE
Simple xml sample cause infinity loop.

### ISSUE THREAD

**Issue by minemaz** [HxJointForces/Hxmr#22]
Simple xml sample cause infinity loop.

This is successfully complete.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ans:A xmlns:ans="*">
	<ans:anotherInnerString>
		<ans:String id="myString"/>
	</ans:anotherInnerString>
</ans:A>
```

but, this is not.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ans:A xmlns:ans="*">
  <ans:anotherInnerString/>
</ans:A>
```

It occurs in the while loop of **src/main/haxe/hxrm/analyzer/NodeAnalyzer.hx**.

**Comment by profelis** [comment]
@minemaz hxmr is deprecated. Try https://github.com/profelis/hml .

**Comment by minemaz** [comment]
Thanks, @profelis
